### ISSUE TITLE
Prepare and show TODOs component when authorized.

### ISSUE THREAD

**Issue by weibeu** [thec0sm0s/TODOx#4]
https://github.com/thec0sm0s/TODOx/blob/80d298718100cafed36ca6808260e8e87df8e050/todox/frontend/src/components/Main.js#L19

The current implementation just shows the authorization/login screen. We need to display the actual TODO interface which is received from the Django REST backend.

**Comment by AnweshaDan** [comment]
I would like to work on this, could you assign me the issue?

**Comment by ankur2753** [comment]
could you assign me the issue ?

**Comment by weibeu** [comment]
@AnweshaDan My bad I forgot to mark issue as assigned. Ankur has already progressed some on it so would you mind to share if you want to work with Python or JS path. That way I will create the next task for development to this project as an issue.

**Comment by AnweshaDan** [comment]
It's ok, I would lie to work with JS.

**Comment by weibeu** [comment]
@AnweshaDan Check if this interests you: https://github.com/thec0sm0s/instant-notes-web/issues/1
Also, this same repository has few more issues, check those as well if you don't like this one.
